### ISSUE TITLE
Stack trace from weird one time crash

### ISSUE THREAD

**Issue by zamanlh** [briandconnelly/seeds#6]
Traceback (most recent call last):
  File "runlettuce.py", line 116, in <module>
    main()
  File "runlettuce.py", line 76, in main
    world = L.World(configfile=cmd_options.configfile, seed=random_seed)
  File "/Library/Frameworks/Python.framework/Versions/6.3/lib/python2.6/site-packages/lettuce/World.py", line 61, in **init**
    self.topology_manager = TopologyManager(self)
  File "/Library/Frameworks/Python.framework/Versions/6.3/lib/python2.6/site-packages/lettuce/TopologyManager.py", line 52, in **init**
    t = CartesianTopology(self.world, topid)
  File "/Library/Frameworks/Python.framework/Versions/6.3/lib/python2.6/site-packages/lettuce/topology/CartesianTopology.py", line 80, in **init**
    periodic_boundaries=self.periodic_boundaries)
  File "/Library/Frameworks/Python.framework/Versions/6.3/lib/python2.6/site-packages/lettuce/topology/CartesianTopology.py", line 148, in build_graph
    p_coords = G.node[potential]['cell'].coords
KeyError: 537

**Comment by zamanlh** [comment]
This is occurring frequently for low expected neighborhood sizes, so I think it is an issue with building the graph when we remove floating nodes.

**Comment by briandconnelly** [comment]
My suspicion is that this happens when a disconnected node gets removed, it isn't removed from the potential neighbor bins, and that deleted node gets considered as a possible neighbor from the bins later on.  Good find!  I'll take care of it.

**Comment by briandconnelly** [comment]
I've fixed this behavior (hoping that it's the cause of this crash).  It'll be pushed and included as part of 1.0.4.
